DEFAULT_HEALTH = 100
DEFAULT_ATTACK_POWER = 10
DEFAULT_STAMINA = 100
DEFAULT_POSITION = 0

MIN_POSITION = 0
MAX_POSITION = 1000

MIN_HEALTH = 50
MIN_ATTACK_POWER = 5
MIN_STAMINA = 50

MAX_HEALTH = 200
MAX_ATTACK_POWER = 50
MAX_STAMINA = 200

MIN_LEG_COUNT = 0
MIN_WING_COUNT = 0
MIN_CLAW_LEVEL = 0
MIN_TEETH_LEVEL = 0

MAX_LEG_COUNT = 10
MAX_WING_COUNT = 10
MAX_CLAW_LEVEL = 10
MAX_TEETH_LEVEL = 10